/**
 * Zentrales Melderegister
 * Zentrales Melderegister
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PatientDTO } from './patientDTO';
import { TestResultDTO } from './testResultDTO';

export interface TestPatientTestResultDTO { 
    entryDate?: string;
    id?: number;
    patientDTO?: PatientDTO;
    patientId?: number;
    resultDate?: string;
    testDate?: string;
    testResultDTO?: TestResultDTO;
    testResultId?: number;
}