/**
 * Zentrales Melderegister
 * Zentrales Melderegister
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserAccountDTO { 
    activated?: boolean;
    activationKey?: string;
    authorities?: Array<UserAccountDTO.AuthoritiesEnum>;
    creationDateTime?: Date;
    firstName?: string;
    id?: number;
    lastName?: string;
    mail?: string;
    passwordHash?: string;
    resetDateTime?: Date;
    resetKey?: string;
}
export namespace UserAccountDTO {
    export type AuthoritiesEnum = 'USER' | 'ADMIN' | 'ANONYMOUS';
    export const AuthoritiesEnum = {
        USER: 'USER' as AuthoritiesEnum,
        ADMIN: 'ADMIN' as AuthoritiesEnum,
        ANONYMOUS: 'ANONYMOUS' as AuthoritiesEnum
    };
}