/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.city_id_seq</code>
     */
    public static final Sequence<Long> CITY_ID_SEQ = new SequenceImpl<Long>("city_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.county_id_seq</code>
     */
    public static final Sequence<Long> COUNTY_ID_SEQ = new SequenceImpl<Long>("county_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.doctor_id_seq</code>
     */
    public static final Sequence<Long> DOCTOR_ID_SEQ = new SequenceImpl<Long>("doctor_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.doctor_patient_id_seq</code>
     */
    public static final Sequence<Long> DOCTOR_PATIENT_ID_SEQ = new SequenceImpl<Long>("doctor_patient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.patient_id_seq</code>
     */
    public static final Sequence<Long> PATIENT_ID_SEQ = new SequenceImpl<Long>("patient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.state_id_seq</code>
     */
    public static final Sequence<Long> STATE_ID_SEQ = new SequenceImpl<Long>("state_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.test_id_seq</code>
     */
    public static final Sequence<Long> TEST_ID_SEQ = new SequenceImpl<Long>("test_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.test_result_id_seq</code>
     */
    public static final Sequence<Long> TEST_RESULT_ID_SEQ = new SequenceImpl<Long>("test_result_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_account_id_seq</code>
     */
    public static final Sequence<Long> USER_ACCOUNT_ID_SEQ = new SequenceImpl<Long>("user_account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
