/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.City;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Country;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Doctor;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.DoctorPatient;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.FlywaySchemaHistory;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Patient;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.State;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Test;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.TestResult;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.UserAccount;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.city</code>.
     */
    public static final City CITY = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public static final Country COUNTRY = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Country.COUNTRY;

    /**
     * The table <code>public.doctor</code>.
     */
    public static final Doctor DOCTOR = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Doctor.DOCTOR;

    /**
     * The table <code>public.doctor_patient</code>.
     */
    public static final DoctorPatient DOCTOR_PATIENT = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.DoctorPatient.DOCTOR_PATIENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.patient</code>.
     */
    public static final Patient PATIENT = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Patient.PATIENT;

    /**
     * The table <code>public.state</code>.
     */
    public static final State STATE = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.State.STATE;

    /**
     * The table <code>public.test</code>.
     */
    public static final Test TEST = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Test.TEST;

    /**
     * The table <code>public.test_result</code>.
     */
    public static final TestResult TEST_RESULT = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.TestResult.TEST_RESULT;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = de.wirvsvirus.zentralesmelderegister.model.jooq.tables.UserAccount.USER_ACCOUNT;
}
