export * from './cityController.service';
import { CityControllerService } from './cityController.service';
export * from './countryController.service';
import { CountryControllerService } from './countryController.service';
export * from './doctorController.service';
import { DoctorControllerService } from './doctorController.service';
export * from './patientController.service';
import { PatientControllerService } from './patientController.service';
export * from './stateController.service';
import { StateControllerService } from './stateController.service';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export * from './testResultController.service';
import { TestResultControllerService } from './testResultController.service';
export * from './userAccountApiController.service';
import { UserAccountApiControllerService } from './userAccountApiController.service';
export * from './userJwtApiController.service';
import { UserJwtApiControllerService } from './userJwtApiController.service';
export const APIS = [CityControllerService, CountryControllerService, DoctorControllerService, PatientControllerService, StateControllerService, TestControllerService, TestResultControllerService, UserAccountApiControllerService, UserJwtApiControllerService];
