/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.City;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends UpdatableRecordImpl<CityRecord> implements Record6<Long, BigDecimal, BigDecimal, String, Long, Long> {

    private static final long serialVersionUID = -197693711;

    /**
     * Setter for <code>public.city.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.city.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.city.coordinates_longitude</code>.
     */
    public void setCoordinatesLongitude(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.city.coordinates_longitude</code>.
     */
    public BigDecimal getCoordinatesLongitude() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.city.coordinates_latitude</code>.
     */
    public void setCoordinatesLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.city.coordinates_latitude</code>.
     */
    public BigDecimal getCoordinatesLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.city.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.city.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.city.country_id</code>.
     */
    public void setCountryId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.city.country_id</code>.
     */
    public Long getCountryId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.city.user_account_id</code>.
     */
    public void setUserAccountId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.city.user_account_id</code>.
     */
    public Long getUserAccountId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, BigDecimal, BigDecimal, String, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, BigDecimal, BigDecimal, String, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return City.CITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return City.CITY.COORDINATES_LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return City.CITY.COORDINATES_LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return City.CITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return City.CITY.COUNTRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return City.CITY.USER_ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getCoordinatesLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getCoordinatesLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getUserAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getCoordinatesLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getCoordinatesLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUserAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value2(BigDecimal value) {
        setCoordinatesLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value3(BigDecimal value) {
        setCoordinatesLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value5(Long value) {
        setCountryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord value6(Long value) {
        setUserAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityRecord values(Long value1, BigDecimal value2, BigDecimal value3, String value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CityRecord
     */
    public CityRecord() {
        super(City.CITY);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    public CityRecord(Long id, BigDecimal coordinatesLongitude, BigDecimal coordinatesLatitude, String name, Long countryId, Long userAccountId) {
        super(City.CITY);

        set(0, id);
        set(1, coordinatesLongitude);
        set(2, coordinatesLatitude);
        set(3, name);
        set(4, countryId);
        set(5, userAccountId);
    }
}
