/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.County;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountyRecord extends UpdatableRecordImpl<CountyRecord> implements Record5<Long, BigDecimal, BigDecimal, String, Long> {

    private static final long serialVersionUID = 1449475008;

    /**
     * Setter for <code>public.county.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.county.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.county.coordinates_longitude</code>.
     */
    public void setCoordinatesLongitude(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.county.coordinates_longitude</code>.
     */
    public BigDecimal getCoordinatesLongitude() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.county.coordinates_latitude</code>.
     */
    public void setCoordinatesLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.county.coordinates_latitude</code>.
     */
    public BigDecimal getCoordinatesLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.county.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.county.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.county.state_id</code>.
     */
    public void setStateId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.county.state_id</code>.
     */
    public Long getStateId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, BigDecimal, BigDecimal, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, BigDecimal, BigDecimal, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return County.COUNTY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return County.COUNTY.COORDINATES_LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return County.COUNTY.COORDINATES_LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return County.COUNTY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return County.COUNTY.STATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getCoordinatesLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getCoordinatesLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getCoordinatesLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getCoordinatesLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getStateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord value2(BigDecimal value) {
        setCoordinatesLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord value3(BigDecimal value) {
        setCoordinatesLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord value5(Long value) {
        setStateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountyRecord values(Long value1, BigDecimal value2, BigDecimal value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountyRecord
     */
    public CountyRecord() {
        super(County.COUNTY);
    }

    /**
     * Create a detached, initialised CountyRecord
     */
    public CountyRecord(Long id, BigDecimal coordinatesLongitude, BigDecimal coordinatesLatitude, String name, Long stateId) {
        super(County.COUNTY);

        set(0, id);
        set(1, coordinatesLongitude);
        set(2, coordinatesLatitude);
        set(3, name);
        set(4, stateId);
    }
}
