/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.DoctorPatient;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorPatientRecord extends UpdatableRecordImpl<DoctorPatientRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1797475557;

    /**
     * Setter for <code>public.doctor_patient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doctor_patient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.doctor_patient.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doctor_patient.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.doctor_patient.doctor_id</code>.
     */
    public void setDoctorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doctor_patient.doctor_id</code>.
     */
    public Long getDoctorId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DoctorPatient.DOCTOR_PATIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DoctorPatient.DOCTOR_PATIENT.PATIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DoctorPatient.DOCTOR_PATIENT.DOCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatientRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatientRecord value2(Long value) {
        setPatientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatientRecord value3(Long value) {
        setDoctorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatientRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DoctorPatientRecord
     */
    public DoctorPatientRecord() {
        super(DoctorPatient.DOCTOR_PATIENT);
    }

    /**
     * Create a detached, initialised DoctorPatientRecord
     */
    public DoctorPatientRecord(Long id, Long patientId, Long doctorId) {
        super(DoctorPatient.DOCTOR_PATIENT);

        set(0, id);
        set(1, patientId);
        set(2, doctorId);
    }
}
