/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.Test;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestRecord extends UpdatableRecordImpl<TestRecord> implements Record6<Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> {

    private static final long serialVersionUID = 390539802;

    /**
     * Setter for <code>public.test.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.test.entry_date</code>.
     */
    public void setEntryDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test.entry_date</code>.
     */
    public OffsetDateTime getEntryDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.test.test_date</code>.
     */
    public void setTestDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.test.test_date</code>.
     */
    public OffsetDateTime getTestDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.test.result_date</code>.
     */
    public void setResultDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.test.result_date</code>.
     */
    public OffsetDateTime getResultDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.test.test_result_id</code>.
     */
    public void setTestResultId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.test.test_result_id</code>.
     */
    public Long getTestResultId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.test.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.test.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Test.TEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field2() {
        return Test.TEST.ENTRY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return Test.TEST.TEST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field4() {
        return Test.TEST.RESULT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Test.TEST.TEST_RESULT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Test.TEST.PATIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component2() {
        return getEntryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getTestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component4() {
        return getResultDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTestResultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value2() {
        return getEntryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getTestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value4() {
        return getResultDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTestResultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getPatientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value2(OffsetDateTime value) {
        setEntryDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value3(OffsetDateTime value) {
        setTestDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value4(OffsetDateTime value) {
        setResultDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value5(Long value) {
        setTestResultId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord value6(Long value) {
        setPatientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestRecord values(Long value1, OffsetDateTime value2, OffsetDateTime value3, OffsetDateTime value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestRecord
     */
    public TestRecord() {
        super(Test.TEST);
    }

    /**
     * Create a detached, initialised TestRecord
     */
    public TestRecord(Long id, OffsetDateTime entryDate, OffsetDateTime testDate, OffsetDateTime resultDate, Long testResultId, Long patientId) {
        super(Test.TEST);

        set(0, id);
        set(1, entryDate);
        set(2, testDate);
        set(3, resultDate);
        set(4, testResultId);
        set(5, patientId);
    }
}
