/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.UserAuthority;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthorityRecord extends TableRecordImpl<UserAuthorityRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = -2052484808;

    /**
     * Setter for <code>public.user_authority.authority</code>.
     */
    public void setAuthority(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_authority.authority</code>.
     */
    public String getAuthority() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_authority.user_account_id</code>.
     */
    public void setUserAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_authority.user_account_id</code>.
     */
    public Long getUserAccountId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserAuthority.USER_AUTHORITY.AUTHORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UserAuthority.USER_AUTHORITY.USER_ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAuthority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getUserAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAuthority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUserAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthorityRecord value1(String value) {
        setAuthority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthorityRecord value2(Long value) {
        setUserAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAuthorityRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAuthorityRecord
     */
    public UserAuthorityRecord() {
        super(UserAuthority.USER_AUTHORITY);
    }

    /**
     * Create a detached, initialised UserAuthorityRecord
     */
    public UserAuthorityRecord(String authority, Long userAccountId) {
        super(UserAuthority.USER_AUTHORITY);

        set(0, authority);
        set(1, userAccountId);
    }
}
