/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records;


import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.UserAccount;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> implements Record10<Long, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> {

    private static final long serialVersionUID = 1687726003;

    /**
     * Setter for <code>public.user_account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_account.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_account.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_account.mail</code>.
     */
    public void setMail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_account.mail</code>.
     */
    public String getMail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_account.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_account.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.user_account.activation_key</code>.
     */
    public void setActivationKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_account.activation_key</code>.
     */
    public String getActivationKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_account.reset_key</code>.
     */
    public void setResetKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_account.reset_key</code>.
     */
    public String getResetKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user_account.reset_date</code>.
     */
    public void setResetDate(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_account.reset_date</code>.
     */
    public OffsetDateTime getResetDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.user_account.create_date_time</code>.
     */
    public void setCreateDateTime(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_account.create_date_time</code>.
     */
    public OffsetDateTime getCreateDateTime() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.user_account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.user_account.last_name</code>.
     */
    public void setLastName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserAccount.USER_ACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserAccount.USER_ACCOUNT.PASSWORD_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserAccount.USER_ACCOUNT.MAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return UserAccount.USER_ACCOUNT.ACTIVATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserAccount.USER_ACCOUNT.ACTIVATION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserAccount.USER_ACCOUNT.RESET_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field7() {
        return UserAccount.USER_ACCOUNT.RESET_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return UserAccount.USER_ACCOUNT.CREATE_DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserAccount.USER_ACCOUNT.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UserAccount.USER_ACCOUNT.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPasswordHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getActivated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getResetKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component7() {
        return getResetDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return getCreateDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPasswordHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getActivated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getResetKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value7() {
        return getResetDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return getCreateDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value2(String value) {
        setPasswordHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value3(String value) {
        setMail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value4(Boolean value) {
        setActivated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value5(String value) {
        setActivationKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value6(String value) {
        setResetKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value7(OffsetDateTime value) {
        setResetDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value8(OffsetDateTime value) {
        setCreateDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value9(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord value10(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserAccountRecord values(Long value1, String value2, String value3, Boolean value4, String value5, String value6, OffsetDateTime value7, OffsetDateTime value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(Long id, String passwordHash, String mail, Boolean activated, String activationKey, String resetKey, OffsetDateTime resetDate, OffsetDateTime createDateTime, String firstName, String lastName) {
        super(UserAccount.USER_ACCOUNT);

        set(0, id);
        set(1, passwordHash);
        set(2, mail);
        set(3, activated);
        set(4, activationKey);
        set(5, resetKey);
        set(6, resetDate);
        set(7, createDateTime);
        set(8, firstName);
        set(9, lastName);
    }
}
