/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables;


import de.wirvsvirus.zentralesmelderegister.model.jooq.Indexes;
import de.wirvsvirus.zentralesmelderegister.model.jooq.Keys;
import de.wirvsvirus.zentralesmelderegister.model.jooq.Public;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records.DoctorPatientRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DoctorPatient extends TableImpl<DoctorPatientRecord> {

    private static final long serialVersionUID = -1797172210;

    /**
     * The reference instance of <code>public.doctor_patient</code>
     */
    public static final DoctorPatient DOCTOR_PATIENT = new DoctorPatient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoctorPatientRecord> getRecordType() {
        return DoctorPatientRecord.class;
    }

    /**
     * The column <code>public.doctor_patient.id</code>.
     */
    public final TableField<DoctorPatientRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('doctor_patient_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.doctor_patient.patient_id</code>.
     */
    public final TableField<DoctorPatientRecord, Long> PATIENT_ID = createField("patient_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.doctor_patient.doctor_id</code>.
     */
    public final TableField<DoctorPatientRecord, Long> DOCTOR_ID = createField("doctor_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.doctor_patient</code> table reference
     */
    public DoctorPatient() {
        this(DSL.name("doctor_patient"), null);
    }

    /**
     * Create an aliased <code>public.doctor_patient</code> table reference
     */
    public DoctorPatient(String alias) {
        this(DSL.name(alias), DOCTOR_PATIENT);
    }

    /**
     * Create an aliased <code>public.doctor_patient</code> table reference
     */
    public DoctorPatient(Name alias) {
        this(alias, DOCTOR_PATIENT);
    }

    private DoctorPatient(Name alias, Table<DoctorPatientRecord> aliased) {
        this(alias, aliased, null);
    }

    private DoctorPatient(Name alias, Table<DoctorPatientRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DoctorPatient(Table<O> child, ForeignKey<O, DoctorPatientRecord> key) {
        super(child, key, DOCTOR_PATIENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DOCTOR_PATIENT_ID_UINDEX, Indexes.DOCTOR_PATIENT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DoctorPatientRecord, Long> getIdentity() {
        return Keys.IDENTITY_DOCTOR_PATIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DoctorPatientRecord> getPrimaryKey() {
        return Keys.DOCTOR_PATIENT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DoctorPatientRecord>> getKeys() {
        return Arrays.<UniqueKey<DoctorPatientRecord>>asList(Keys.DOCTOR_PATIENT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DoctorPatientRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DoctorPatientRecord, ?>>asList(Keys.DOCTOR_PATIENT__DOCTOR_PATIENT_PATIENT_ID_FK, Keys.DOCTOR_PATIENT__DOCTOR_PATIENT_DOCTOR_ID_FK);
    }

    public Patient patient() {
        return new Patient(this, Keys.DOCTOR_PATIENT__DOCTOR_PATIENT_PATIENT_ID_FK);
    }

    public Doctor doctor() {
        return new Doctor(this, Keys.DOCTOR_PATIENT__DOCTOR_PATIENT_DOCTOR_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatient as(String alias) {
        return new DoctorPatient(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DoctorPatient as(Name alias) {
        return new DoctorPatient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DoctorPatient rename(String name) {
        return new DoctorPatient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DoctorPatient rename(Name name) {
        return new DoctorPatient(name, null);
    }
}
