/*
 * This file is generated by jOOQ.
 */
package de.wirvsvirus.zentralesmelderegister.model.jooq.tables;


import de.wirvsvirus.zentralesmelderegister.model.jooq.Indexes;
import de.wirvsvirus.zentralesmelderegister.model.jooq.Keys;
import de.wirvsvirus.zentralesmelderegister.model.jooq.Public;
import de.wirvsvirus.zentralesmelderegister.model.jooq.tables.records.TestResultRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestResult extends TableImpl<TestResultRecord> {

    private static final long serialVersionUID = 147484354;

    /**
     * The reference instance of <code>public.test_result</code>
     */
    public static final TestResult TEST_RESULT = new TestResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestResultRecord> getRecordType() {
        return TestResultRecord.class;
    }

    /**
     * The column <code>public.test_result.id</code>.
     */
    public final TableField<TestResultRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('test_result_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.test_result.description</code>.
     */
    public final TableField<TestResultRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.test_result</code> table reference
     */
    public TestResult() {
        this(DSL.name("test_result"), null);
    }

    /**
     * Create an aliased <code>public.test_result</code> table reference
     */
    public TestResult(String alias) {
        this(DSL.name(alias), TEST_RESULT);
    }

    /**
     * Create an aliased <code>public.test_result</code> table reference
     */
    public TestResult(Name alias) {
        this(alias, TEST_RESULT);
    }

    private TestResult(Name alias, Table<TestResultRecord> aliased) {
        this(alias, aliased, null);
    }

    private TestResult(Name alias, Table<TestResultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TestResult(Table<O> child, ForeignKey<O, TestResultRecord> key) {
        super(child, key, TEST_RESULT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEST_RESULT_ID_UINDEX, Indexes.TEST_RESULT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TestResultRecord, Long> getIdentity() {
        return Keys.IDENTITY_TEST_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TestResultRecord> getPrimaryKey() {
        return Keys.TEST_RESULT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TestResultRecord>> getKeys() {
        return Arrays.<UniqueKey<TestResultRecord>>asList(Keys.TEST_RESULT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestResult as(String alias) {
        return new TestResult(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TestResult as(Name alias) {
        return new TestResult(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestResult rename(String name) {
        return new TestResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestResult rename(Name name) {
        return new TestResult(name, null);
    }
}
